name: shape_continuum
channels:
  - file:///home/sebastian/miniconda3/conda-bld
  - defaults
  - sebp
  - pytorch
  - conda-forge
dependencies:
  - absl-py==0.10.0
  - cachetools==4.1.1
  - chardet==3.0.4
  - cudatoolkit==10.2.89
  - google-auth==1.22.1
  - google-auth-oauthlib==0.4.1
  - grpcio
  - h5py==2.10.0
  - idna==2.10
  - importlib-metadata==2.0.0
  - networkx==2.5
  - numpy==1.19.1
  - markdown==3.3
  - oauthlib==3.1.0
  - opencv==4.4.0
  - openmesh-python==1.1.3
  - pandas==1.0.5
  - pip
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pyopengl==3.1.5
  - python=3.7
  - pytorch==1.5.1
  - pyyaml==5.3.1
  - pyzmq==19.0.2
  - requests==2.24.0
  - requests-oauthlib==1.3.0
  - rsa==4.6
  - torch-cluster==1.5.7
  - torch-geometric==1.6.1
  - torch-scatter==2.0.5
  - torch-sparse==0.6.7
  - scikit-learn==0.23.2
  - scikit-survival
  - scipy==1.5.2
  - torchvision==0.6.1
  - tqdm==4.48.2
  - urllib3==1.25.10
  - werkzeug==1.0.1
  - zipp==3.3.0
  - pip:
    - tensorboard==2.3.0
    - https://github.com/MPI-IS/mesh/releases/download/v0.4/psbody_mesh-0.4-cp37-cp37m-linux_x86_64.whl
