{% set name = "torch-cluster" %}
{% set version = "1.5.7" %}
{% set sha256 = "62a3ec1bebadda1a4a2c867203f4c957b9c0b9d11ffb03b40b8ea9f95a0a4d3b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: torch_cluster-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/torch_cluster/torch_cluster-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  script_env:
    - CUDA_VERSION
    - CUDA_HOME
  string: py3.7_cuda10.2.89_cudnn7.6.5_0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    #- magma-cuda102==2.5.2
    - numpy
    - setuptools
    - scipy
    - pytest-runner
    - pytorch==1.5.1

  run:
    - python
    - cudatoolkit >=10.2,<10.3
    - scipy >=1.0
    - setuptools
    - pytorch==1.5.1

test:
  # Python imports
  imports:
    - torch_cluster

about:
  home: https://github.com/rusty1s/pytorch_cluster
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'PyTorch Extension Library of Optimized Graph Cluster Algorithms'

extra:
  recipe-maintainers:
    - sebp
