{% set name = "torch-scatter" %}
{% set version = "2.0.5" %}
{% set sha256 = "148fbe634fb9e9465dbde2ab337138f63650ed8abbac42bb3f565e3fe92e9b2f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: scatter-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/torch_scatter/torch_scatter-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  script_env:
    - CUDA_VERSION
    - CUDA_HOME
  string: py3.7_cuda10.2.89_cudnn7.6.5_0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    #- magma-cuda100==2.5.0
    - numpy
    - setuptools
    - pytest-runner
    - pytorch==1.5.1

  run:
    - python
    - cudatoolkit >=10.2,<10.3
    - setuptools
    - pytorch==1.5.1

test:
  # Python imports
  imports:
    - torch_scatter
    - torch_scatter.utils

about:
  home: https://github.com/rusty1s/pytorch_scatter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'PyTorch Extension Library of Optimized Scatter Operations'

extra:
  recipe-maintainers:
    - sebp
